apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - bootloader.yaml
  - db.yaml
  - pod-sweeper.yaml
  - scheduler.yaml
  - secret-gcs-log-creds.yaml
  - scheduler-service-account.yaml
  - server.yaml
  - temporal.yaml
  - webapp.yaml
  - worker.yaml
  - metrics-reporter.yaml
