apiVersion: apps/v1
kind: Deployment
metadata:
  name: airbyte-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      airbyte: metrics
  template:
    metadata:
      labels:
        airbyte: metrics
    spec:
      containers:
        - name: airbyte-metrics-container
          image: airbyte/metrics-reporter
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: airbyte-secrets
                  key: DATABASE_PASSWORD
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: airbyte-env
                  key: DATABASE_URL
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: airbyte-secrets
                  key: DATABASE_USER
