---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}-webapp
  labels:
    {{- include "airbyte.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.webapp.replicaCount }}
  selector:
    matchLabels:
      airbyte: webapp
  template:
    metadata:
      labels:
        airbyte: webapp
      {{- if .Values.webapp.podAnnotations }}
      annotations:
        {{- include "common.tplvalues.render" (dict "value" .Values.webapp.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.webapp.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.webapp.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.webapp.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.webapp.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.webapp.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.webapp.affinity "context" $) | nindent 8 }}
      {{- end }}
      containers:
      - name: airbyte-webapp-container
        image: {{ include "airbyte.webappImage" . }}
        imagePullPolicy: "{{ .Values.webapp.image.pullPolicy }}"
        env:
        - name: AIRBYTE_VERSION
          valueFrom:
            configMapKeyRef:
              name: {{ include "common.names.fullname" . }}-env
              key: AIRBYTE_VERSION
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "common.names.fullname" . }}-env
              key: API_URL
        - name: TRACKING_STRATEGY
          valueFrom:
            configMapKeyRef:
              name: {{ include "common.names.fullname" . }}-env
              key: TRACKING_STRATEGY
        - name: SENTRY_DSN
          valueFrom:
            configMapKeyRef:
              name: {{ include "common.names.fullname" . }}-env
              key: SENTRY_DSN
        - name: PAPERCUPS_STORYTIME
          valueFrom:
            configMapKeyRef:
              name: {{ include "common.names.fullname" . }}-env
              key: PAPERCUPS_STORYTIME
        - name: FULLSTORY
          valueFrom:
            configMapKeyRef:
              name: {{ include "common.names.fullname" . }}-env
              key: FULLSTORY
        - name: IS_DEMO
          valueFrom:
            configMapKeyRef:
              name: {{ include "common.names.fullname" . }}-env
              key: IS_DEMO
        {{- if .Values.datadog.enabled }}
        - name: DD_AGENT_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ include "common.names.fullname" . }}-env
              key: DD_AGENT_HOST
        - name: DD_DOGSTATSD_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ include "common.names.fullname" . }}-env
              key: DD_DOGSTATSD_PORT
        - name: PUBLISH_METRICS
          valueFrom:
            configMapKeyRef:
              name: {{ include "common.names.fullname" . }}-env
              key: PUBLISH_METRICS
        {{- end }}
        - name: INTERNAL_API_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ include "common.names.fullname" . }}-env
              key: INTERNAL_API_HOST
        - name: CONTAINER_ORCHESTRATOR_ENABLED
          valueFrom:
            configMapKeyRef:
              name: {{ include "common.names.fullname" . }}-env
              key: CONTAINER_ORCHESTRATOR_ENABLED
        - name: MAX_SYNC_WORKERS
          valueFrom:
            configMapKeyRef:
              name: {{ include "common.names.fullname" . }}-env
              key: MAX_SYNC_WORKERS
        - name: MAX_SPEC_WORKERS
          valueFrom:
            configMapKeyRef:
              name: {{ include "common.names.fullname" . }}-env
              key: MAX_SPEC_WORKERS
        - name: MAX_CHECK_WORKERS
          valueFrom:
            configMapKeyRef:
              name: {{ include "common.names.fullname" . }}-env
              key: MAX_CHECK_WORKERS
        - name: MAX_DISCOVER_WORKERS
          valueFrom:
            configMapKeyRef:
              name: {{ include "common.names.fullname" . }}-env
              key: MAX_DISCOVER_WORKERS
        {{- if .Values.webapp.extraEnv }}
        {{ .Values.webapp.extraEnv | toYaml | nindent 8 }}
        {{- end }}
        {{- if .Values.webapp.livenessProbe.enabled }}
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: {{ .Values.webapp.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.webapp.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.webapp.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.webapp.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.webapp.livenessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.webapp.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: http
          initialDelaySeconds: {{ .Values.webapp.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.webapp.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.webapp.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.webapp.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.webapp.readinessProbe.failureThreshold }}
        {{- end }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        {{- if .Values.webapp.resources }}
        resources: {{- toYaml .Values.webapp.resources | nindent 10 }}
        {{- end }}
        {{- if .Values.webapp.containerSecurityContext }}
        securityContext: {{- toYaml .Values.webapp.containerSecurityContext | nindent 10 }}
        {{- end }}
        volumeMounts:
        {{- if .Values.webapp.extraVolumeMounts }}
  {{ toYaml .Values.webapp.extraVolumeMounts | nindent 8 }}
        {{- end }}
      volumes:
      {{- if .Values.webapp.extraVolumes }}
{{ toYaml .Values.webapp.extraVolumes | nindent 6 }}
      {{- end }}
