apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-secrets
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1"
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.logs.accessKey.password | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.logs.secretKey.password | quote }}
  {{- if eq $.Values.common.stateStorage.type "s3" }}
  STATE_STORAGE_S3_ACCESS_KEY: {{ .Values.common.stateStorage.s3.key | quote }}
  STATE_STORAGE_S3_SECRET_ACCESS_KEY: {{ .Values.common.stateStorage.s3.secret | quote }}
  {{- end }}
  {{- if eq $.Values.common.stateStorage.type "minio" }}
  STATE_STORAGE_MINIO_ACCESS_KEY: {{ .Values.common.stateStorage.minio.key | quote }}
  STATE_STORAGE_MINIO_SECRET_ACCESS_KEY: {{ .Values.common.stateStorage.minio.secret | quote }}
  {{- end }}
  {{ if and (not .Values.postgresql.enabled) (eq .Values.externalDatabase.existingSecret "") -}}
  DATABASE_PASSWORD: {{ .Values.externalDatabase.password | quote }}
  {{ end -}}
  DATABASE_USER: {{ include "airbyte.database.user" . }}
  {{- if .Values.vault.enabled }}
  VAULT_AUTH_TOKEN: {{ .Values.vault.token | quote }}
  {{- end }}
